[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "jupyter-server>=2.21.0",
    "jupyterlab>=4.6.3",
    "notebook>=7.6.2",
    "pandas>=3.0.5",
    "psycopg2>=2.9.13",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary,pool]>=3.3.5",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.0.53",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.6.0",
]
